version: '3.7'
services:
  backend:
    container_name: backend
    build: ./backend/
    command: python manage.py runserver 0.0.0.0:8000
    entrypoint: /django/entrypoint.sh
    volumes:
      - ./backend/:/backend/
    ports:
      - 8000:8000
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"